name: baws-pipeline
# must match repo name defined in codecommit.
repoNameReference: baws-app
branchToWatch: master
# Must match `name` under ecs.tasks.name
taskNameReference: baws-app
# must match `name` under ecs.clusterName
clusterNameReference: baws-cluster