name: baws-pipeline
type: ecs
# must match repo name defined in codecommit.
repoNameReference: baws-app
branchToWatch: master
# This can optionally be an existing S3 bucket,
# but a bucket configured in this CDK is recommended.
bucketNameReference: baws-assets
# must match `name` under ecs.clusterName
createBuildStage: true
# deploymentPath: app