name: phpmyadmin
desiredCount: 1
imageURI: phpmyadmin/phpmyadmin
listeners:
  - type: forward
    priority: 1000
    listenerPort: 10000
    hosts:
    - "*.example.com"
    - example.com
createECR: false
type: ec2
hardMemoryLimit: 512
softMemoryLimit: 128
hostPort: 0
containerPort: 80
cpuUnits: 256
logRegion: us-east-1
# values passed directly to the container
# Default value of "db-host" is set by rds.dbHostParamName config value.
params:
  PMA_HOST: db-host